### ISSUE TITLE
백앤드 작업 환경 동기화

### ISSUE THREAD

**Issue by greenrain78** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#104]
백앤드 작업 환경 동기화를 위해

flake8과 black를 적용
예시는 vscode server를 기준으로 작성

실행환경은 docker로 실행

**Comment by greenrain78** [comment]
{
    "python.pythonPath": "/usr/bin/",
    "python.defaultInterpreterPath": "/usr/bin/python3",
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": ["--max-line-length=120"],
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/usr/bin/black",
    "python.formatting.blackArgs": ["--line-length=160"],
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": null,
        "editor.tabSize": 4
    }
}

**Comment by Jun0zo** [comment]
오케이
