### ISSUE TITLE
fastapi와 nodejs 통합 작업

### ISSUE THREAD

**Issue by dos-m0nk3y** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#113]
fastapi와 nodejs 통합 작업

**Comment by greenrain78** [comment]
프론트
vue 프로젝트를 npm run build로 정적파일로 빌드
빌드된 파일들을 백앤드로 복사

백앤드
nginx unit 으로 fastapi와 연결
nginx unit python 이미지에 fastapi 코드를 복사하여 배포

프론트랑 백앤드
프론트에서 빌드한 파일들을 fastapi의 static 파일로 전달

**Comment by greenrain78** [comment]
통합 완료
deploy버전과 dev 버전을 별도로 분리하여 프론트와 백앤드 결합함
dev/hotfix3 branch 참고
