### ISSUE TITLE
도커 start.sh 실행 오류

### ISSUE THREAD

**Issue by dos-m0nk3y** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#201]
bash start.sh --server

[+] run web camera
omil_db is up-to-date
Starting omil_web    ... done
Starting omil_camera ... done
Attaching to omil_web, omil_camera
omil_web      | Traceback (most recent call last):
omil_web      |   File "/usr/local/bin/uvicorn", line 8, in <module>
omil_web      |     sys.exit(main())
omil_web      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
omil_web      |     return self.main(*args, **kwargs)
omil_web      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
omil_web      |     rv = self.invoke(ctx)
omil_web      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
omil_web      |     return ctx.invoke(self.callback, **ctx.params)
omil_web      |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
omil_web      |     return __callback(*args, **kwargs)
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 408, in main
omil_web      |     run(
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
omil_web      |     server.run()
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
omil_web      |     return asyncio.run(self.serve(sockets=sockets))
omil_web      |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
omil_web      |     return loop.run_until_complete(main)
omil_web      |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
omil_web      |     config.load()
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 442, in load
omil_web      |     self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
omil_web      |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 142, in create_ssl_context
omil_web      |     ctx.load_cert_chain(certfile, keyfile, get_password)
omil_web      | FileNotFoundError: [Errno 2] No such file or directory
omil_camera   | Traceback (most recent call last):
omil_camera   |   File "/usr/local/bin/uvicorn", line 8, in <module>
omil_camera   |     sys.exit(main())
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
omil_camera   |     return self.main(*args, **kwargs)
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
omil_camera   |     rv = self.invoke(ctx)
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
omil_camera   |     return ctx.invoke(self.callback, **ctx.params)
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
omil_camera   |     return __callback(*args, **kwargs)
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 408, in main
omil_camera   |     run(
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
omil_camera   |     server.run()
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
omil_camera   |     return asyncio.run(self.serve(sockets=sockets))
omil_camera   |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
omil_camera   |     return loop.run_until_complete(main)
omil_camera   |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
omil_camera   |     config.load()
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 442, in load
omil_camera   |     self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
omil_camera   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 142, in create_ssl_context
omil_camera   |     ctx.load_cert_chain(certfile, keyfile, get_password)
omil_camera   | FileNotFoundError: [Errno 2] No such file or directory
omil_web exited with code 1
omil_camera exited with code 1

**Comment by greenrain78** [comment]
해당 내용 확인 및 1차 수정 완료

**Comment by greenrain78** [comment]
cicd 브랜치  3962cef6308ce61a0aec1e2ad26ce57f4af2d0f2 커밋에서 해당 내역 수정 확인
브랜치 병합 중 잘못 처리된 것이 원인으로 파악됨

**Comment by greenrain78** [comment]
2차 수정 완료

**Comment by greenrain78** [comment]
테스트 목록
1. 기본 환경에서 테스트
2. 컨테이너 제거 및 이미지 재빌드 후 테스트
3. git clone을 다시한 후 테스트
4. VM에서 테스트
5. VM을 초기화 후 테스트

**Comment by greenrain78** [comment]
해당 문제의 원인은 cicd 브랜치와 병합하는 과정에서 코드가 잘못 반영된 것 같습니다.
그래서 테스트를 development브랜치에 pull request 후에도 확인해야 되지 않을까 생각됩니다.

**Comment by dos-m0nk3y** [comment]
확인완료
해결 완료
