### ISSUE TITLE
회원가입 페이지 엔드포인트 결합

### ISSUE THREAD

**Issue by dos-m0nk3y** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#210]
1. 부대조회 기능
GET /unit/

2. 회원가입 기능
POST /user/

**Comment by dos-m0nk3y** [comment]
확인해보고 이상없으면 닫아주세용

**Comment by biyotteu** [comment]
소속(육해공해병국직), 계급을 코드로 받으시던데 그러면 소속 테이블, 계급 테이블 get 기능이 필요할 듯 합니다.
그리고 아이디 중복 시 에러코드 리턴이 필요할 듯하고, 암호 해싱은 프론트에서 해서 보내는게 맞는거같습니다.

**Comment by dos-m0nk3y** [comment]
아이디 및 Unique 키 중복시에 {"success":False, "message":"unique key constraint fail"} 반환 중인데 각 키별로 에러메시지가 필요한거면 말해줘.
암호는 백에서 받아서 해싱 해서 DB에 넣고 있는데 프런트에서 할 필요가 있을까?

**Comment by dos-m0nk3y** [comment]
#238 각종 테이블들에 get 기능 추가 완료

**Comment by dos-m0nk3y** [comment]
#242 회원가입 오류메시지 구체화
