### ISSUE TITLE
백엔드 에러 로그

### ISSUE THREAD

**Issue by biyotteu** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#214]
omil_web     | INFO:     172.19.0.1:58298 - "GET / HTTP/1.1" 404 Not Found
omil_web     | INFO:     172.19.0.1:58298 - "GET / HTTP/1.1" 404 Not Found
omil_web     | INFO:     172.19.0.1:63500 - "GET /user/ HTTP/1.1" 500 Internal Server Error
omil_web     | ERROR:    Exception in ASGI application
omil_web     | Traceback (most recent call last):
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
omil_web     |     return fn()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 320, in connect
omil_web     |     return _ConnectionFairy._checkout(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
omil_web     |     fairy = _ConnectionRecord.checkout(pool)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
omil_web     |     rec = pool._do_get()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
omil_web     |     self._dec_overflow()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
omil_web     |     compat.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
omil_web     |     return self._create_connection()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
omil_web     |     return _ConnectionRecord(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
omil_web     |     self.__connect()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __connect
omil_web     |     pool.logger.debug("Error on connect(): %s", e)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
omil_web     |     compat.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
omil_web     |     self.dbapi_connection = connection = pool._invoke_creator(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
omil_web     |     return dialect.connect(*cargs, **cparams)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
omil_web     |     return self.dbapi.connect(*cargs, **cparams)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
omil_web     |     return Connection(*args, **kwargs)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
omil_web     |     super().__init__(*args, **kwargs2)
omil_web     | MySQLdb.OperationalError: (2005, "Unknown MySQL server host '@db' (-2)")
omil_web     | 
omil_web     | The above exception was the direct cause of the following exception:
omil_web     | 
omil_web     | Traceback (most recent call last):
omil_web     |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
omil_web     |     result = await app(  # type: ignore[func-returns-value]
omil_web     |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
omil_web     |     return await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
omil_web     |     await super().__call__(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
omil_web     |     await self.middleware_stack(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
omil_web     |     raise exc
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
omil_web     |     await self.app(scope, receive, _send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
omil_web     |     raise exc
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
omil_web     |     await self.app(scope, receive, sender)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
omil_web     |     raise e
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
omil_web     |     await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
omil_web     |     await route.handle(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
omil_web     |     await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
omil_web     |     response = await func(request)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
omil_web     |     raw_response = await run_endpoint_function(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
omil_web     |     return await run_in_threadpool(dependant.call, **values)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
omil_web     |     return await anyio.to_thread.run_sync(func, *args)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
omil_web     |     return await get_asynclib().run_sync_in_worker_thread(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
omil_web     |     return await future
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
omil_web     |     result = context.run(func, *args)
omil_web     |   File "/backend/src/./app/api/endpoints/user.py", line 27, in get_user
omil_web     |     return crud.get_user(db, flt)
omil_web     |   File "/backend/src/./app/crud/user.py", line 49, in get_user
omil_web     |     return user.all()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2772, in all
omil_web     |     return self._iter().all()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
omil_web     |     result = self.session.execute(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
omil_web     |     conn = self._connection_for_bind(bind)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
omil_web     |     return self._transaction._connection_for_bind(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
omil_web     |     conn = bind.connect()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
omil_web     |     return self._connection_cls(self, close_with_result=close_with_result)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
omil_web     |     else engine.raw_connection()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
omil_web     |     return self._wrap_pool_connect(self.pool.connect, _connection)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
omil_web     |     Connection._handle_dbapi_exception_noconnection(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
omil_web     |     util.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
omil_web     |     return fn()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 320, in connect
omil_web     |     return _ConnectionFairy._checkout(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
omil_web     |     fairy = _ConnectionRecord.checkout(pool)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
omil_web     |     rec = pool._do_get()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
omil_web     |     self._dec_overflow()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
omil_web     |     compat.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
omil_web     |     return self._create_connection()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
omil_web     |     return _ConnectionRecord(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
omil_web     |     self.__connect()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 678, in __connect
omil_web     |     pool.logger.debug("Error on connect(): %s", e)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
omil_web     |     compat.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
omil_web     |     self.dbapi_connection = connection = pool._invoke_creator(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
omil_web     |     return dialect.connect(*cargs, **cparams)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
omil_web     |     return self.dbapi.connect(*cargs, **cparams)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect
omil_web     |     return Connection(*args, **kwargs)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
omil_web     |     super().__init__(*args, **kwargs2)
omil_web     | sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (2005, "Unknown MySQL server host '@db' (-2)")
omil_web     | (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by dos-m0nk3y** [comment]
db 컨테이너 생성 혹은 연결 오류로 추정

**Comment by greenrain78** [comment]
백앤드 연결시 @ 로 인해 password를 인식하지 못하는 문제로 파악함
sqlalchemy에서 db와 연결시  처리가 필요해 보임
-  urllib.parse.quote_plus(db_password)

https://asecurity.dev/entry/Python-SQLAlchemy-pymysql-%EC%82%AC%EC%9A%A9

**Comment by dos-m0nk3y** [comment]
Unknown MySQL server host '@db' 으로부터 db가 호스트로 인식이 안된것으로 추정
비밀번호의 문제가 아닌것으로 판단됨

**Comment by dos-m0nk3y** [comment]
#224 접속 오류 해결
