### ISSUE TITLE
로그인 페이지 엔드포인트 결합

### ISSUE THREAD

**Issue by dos-m0nk3y** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#215]
1. 로그인 기능
POST /login/access-token/

2. JWT를 이용한 유저 정보 확인 기능
POST /login/test-token/

**Comment by biyotteu** [comment]
제가 형식을 잘못맞춘지 잘 모르겠습니다.
`
{
    "username":"admin12345",
    "password":"admin1234@"
}
`
를 request body에 넣고 post를 날리면 422 에러가 돌아옵니다
`
{
    "detail": [
        {
            "loc": [
                "body",
                "username"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        },
        {
            "loc": [
                "body",
                "password"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
`
아이디, 비번이 없다고 뜨는거같은데...... request body 제가 틀린 부분이 있겠습니까???

**Comment by biyotteu** [comment]
<img width="845" alt="스크린샷 2022-10-16 오전 2 08 47" src="https://user-images.githubusercontent.com/32426765/195999167-16c1a5ae-8aab-49d6-a524-1f50fbfbb332.png">

**Comment by dos-m0nk3y** [comment]
OTP 대응가능한 FastAPI 모듈을 사용중이라 JSON이 아니라 POST로 넘겨줘야되.
username=user&password=pass 양식으로 주면 인식 할듯.
