### ISSUE TITLE
person detector 수정사항

### ISSUE THREAD

**Issue by greenrain78** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#227]
1. index error
 - 사진 첨부
 - 사진과 같이 에러가 발생했습니다.
 - 그래서 [[], []]로 되어 있어 [0]로 값을 꺼내어 동작시켰더니 정상동작은 합니다.
 - 해당 부분에서 저렇게 수정된 경우 코드 로직에 문제가 없는지 확인이 필요해 보입니다.

2. x, y 값이 None 인경우 예외처리
 - 사람이 없는 경우 ai 코드에서 에러가 발생하여 예외처리가 필요할 것 같습니다.
 - 그냥 에러없이 None값을 보내주셔도 되고 boolean으로 처리해도 괜찮을 것 같습니다.
자세한 내용은 카톡으로 보냈습니다.

**Comment by Jun0zo** [comment]
"1" 에러의 경우[0]하니까 index out of range 에러가 떠서 인덱싱 부분을 삭제했는데 정상작동합니다...
아마 라이브러리 버전이 달라서인 것 같습니다. 아래는 제 opencv 버전입니다.

opencv-python==4.6.0.66

**Comment by greenrain78** [comment]
opencv-python 버전 문제인 것을 확인 했습니다.

**Comment by Jun0zo** [comment]
버전 바꾸면 정상작동하나요?

**Comment by greenrain78** [comment]
넵 정상작동합니다.
