### ISSUE TITLE
테스트 케이스 생성 오류

### ISSUE THREAD

**Issue by biyotteu** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#255]
omil_web     | INFO:     172.18.0.1:57164 - "POST /stats/test-case HTTP/1.1" 500 Internal Server Error
omil_web     | ERROR:    Exception in ASGI application
omil_web     | Traceback (most recent call last):
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
omil_web     |     self.dialect.do_execute(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
omil_web     |     cursor.execute(statement, parameters)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
omil_web     |     res = self._query(query)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
omil_web     |     db.query(q)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
omil_web     |     _mysql.connection.query(self, query)
omil_web     | MySQLdb.IntegrityError: (1364, "Field 'image_path' doesn't have a default value")
omil_web     | 
omil_web     | The above exception was the direct cause of the following exception:
omil_web     | 
omil_web     | Traceback (most recent call last):
omil_web     |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
omil_web     |     result = await app(  # type: ignore[func-returns-value]
omil_web     |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
omil_web     |     return await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
omil_web     |     await super().__call__(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
omil_web     |     await self.middleware_stack(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
omil_web     |     raise exc
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
omil_web     |     await self.app(scope, receive, _send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
omil_web     |     await self.simple_response(scope, receive, send, request_headers=headers)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
omil_web     |     await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
omil_web     |     raise exc
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
omil_web     |     await self.app(scope, receive, sender)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
omil_web     |     raise e
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
omil_web     |     await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__
omil_web     |     await route.handle(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle
omil_web     |     await self.app(scope, receive, send)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
omil_web     |     response = await func(request)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
omil_web     |     raw_response = await run_endpoint_function(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
omil_web     |     return await run_in_threadpool(dependant.call, **values)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
omil_web     |     return await anyio.to_thread.run_sync(func, *args)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
omil_web     |     return await get_asynclib().run_sync_in_worker_thread(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
omil_web     |     return await future
omil_web     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
omil_web     |     result = context.run(func, *args)
omil_web     |   File "/backend/src/./app/api/endpoints/statistics.py", line 16, in create_test_case
omil_web     |     return crud.create_test_case(db)
omil_web     |   File "/backend/src/./app/crud/statistics.py", line 25, in create_test_case
omil_web     |     db.commit()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
omil_web     |     self._transaction.commit(_to_root=self.future)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
omil_web     |     self._prepare_impl()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
omil_web     |     self.session.flush()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
omil_web     |     self._flush(objects)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3526, in _flush
omil_web     |     transaction.rollback(_capture_exception=True)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
omil_web     |     compat.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
omil_web     |     flush_context.execute()
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
omil_web     |     rec.execute(self)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
omil_web     |     util.preloaded.orm_persistence.save_obj(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
omil_web     |     _emit_insert_statements(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
omil_web     |     result = connection._execute_20(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
omil_web     |     return meth(self, args_10style, kwargs_10style, execution_options)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
omil_web     |     return connection._execute_clauseelement(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
omil_web     |     ret = self._execute_context(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
omil_web     |     self._handle_dbapi_exception(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
omil_web     |     util.raise_(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
omil_web     |     raise exception
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
omil_web     |     self.dialect.do_execute(
omil_web     |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
omil_web     |     cursor.execute(statement, parameters)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
omil_web     |     res = self._query(query)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
omil_web     |     db.query(q)
omil_web     |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
omil_web     |     _mysql.connection.query(self, query)
omil_web     | sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1364, "Field 'image_path' doesn't have a default value")
omil_web     | [SQL: INSERT INTO access_log (military_unit, access_time) VALUES (%s, %s)]
omil_web     | [parameters: (5, datetime.datetime(2022, 5, 24, 16, 11, 12, 418539))]
omil_web     | (Background on this error at: https://sqlalche.me/e/14/gkpj)

**Comment by dos-m0nk3y** [comment]
데이터베이스 구조 변경으로 인해 새롭게 빌드를 해야됨
