### ISSUE TITLE
보안서약서 제출

### ISSUE THREAD

**Issue by Jun0zo** [osamhack2022/WEB_CLOUD_OmilZomil_NAVYeffect#42]
보안서약서 제출해야하는데...
10월 4일까지 아닌가요?

**Comment by Namhoon-Cho** [comment]
'모두싸인'이라는 알림톡에서 [2022 국방분야 SW-AI 역량강화님의 서명 요청] 이라며 "참가자용 보안서약서_2022 군장병 공개SW 온라인 해커톤"에 서명해달라고 왔을 겁니다.
 저는 9월 20일에 왔으며, 10월 04일 11시 46분이 지나면 서명할 수 없을 것이고, 그곳에서 개인이 서명 완료하면 됩니다. 모 팀원과 같이 OSAM 운영 사무국 측에서 추가적인 연락을 요구한 경우, 이미 그때 답변하긴 했지만 아직 개인에게 톡이 오지 않았다면 제게 말씀해주십시오. OSAM측에 문의해보겠습니다.
 결론적으로 10월 4일까지 모든 멤버가 서명 완료되어야할 것입니다.

**Comment by Jun0zo** [comment]
아직안와쎠여...
